### PR TITLE
Fix delegation amounts in delegators table

### LINKED ISSUE #164: Incorrect display of delegation amounts in delegates profiles
## Description
Celo Mondo is not showing up correctly the delegations to the profiles, here an example
Image

## Environment

- Celo Mondo app version
- Operating System
- Browser: ArcBrowser & GoogleChrome too
- Wallet

### PR DESCRIPTION
**Pull request by shazarre**
This PR fixes incorrect/not all showing delegations in the delegators table for a delegatee.

Fixes #164 

**How to QA**

Compare `0x31cd90C2788f3e390d2Bb72871f5aD3F1a4B22a1` delegators (`/delegate/0x31cd90C2788f3e390d2Bb72871f5aD3F1a4B22a1` on preview)

vs https://mondo.celo.org/delegate/0x31cd90C2788f3e390d2Bb72871f5aD3F1a4B22a1

and notice the difference in delegation amounts, now they (taking into account possible rounding differences) should add up to the value displayed under `Delegated`

Same for `0xFEF5A1A2b3754A2F53161EaaAcb3EB889F004d4a`, but this time notice that the missing delegator is displayed as well (as reported in [the original issue](https://github.com/celo-org/celo-mondo/issues/164)).

### CODE REVIEW

File: src/features/delegation/hooks/useDelegators.ts [hunk 1]
```diff
@@ -32,52 +40,72 @@ export function useDelegators(delegateAddress?: Address) {
...
+  const allDelegators: Address[] = [];
+  reduceLogs(allDelegators, delegateEvents);
+
+  // Filter out duplicates
+  const allDelegatorsUnique = Array.from(new Set(allDelegators));
+
+  // Fetch the amount of gold delegated by each delegator in parallel
+  const allDelegatorsAndAmounts: [string, bigint][] = await Promise.all(
+    allDelegatorsUnique.map(async (address) => {
+      const [_, amount] = await client.readContract({
```
Comment (aaronmgdr) [inline src/features/delegation/hooks/useDelegators.ts:69]: could probably use multicall here

**Review by aaronmgdr — APPROVED** [review]
