### PR TITLE
fix: handle cases where proposals are passing but still show expired

### LINKED ISSUE #347: Proposals shows state "Voting" after voting period ends.
## Description
Proposals are showing _**"Voting"**_ label after the voting period ends, and they are in the _**"Approval/Execution"**_ period.

You can see here for example proposal 260 at the time of this report 1:15 PM Sat 1st Nov (UTC-5) that in Mondo it said  _"Expired 21 hours ago"_ (that's right) it expired at 3:25 PM Friday 31st Oct (past day) you can check that also in the image from celoCLI. But still Mondo is showing **_"Voting"_** tag. 

After a proposal ends the Voting Stage it should shows **"Approval/Execution"**

Image

Image

### PR DESCRIPTION
**Pull request by nicolasbrugneaux**
[Fixes #347]

This handles the cases where a proposal was voted on, then time runs out, no blockchain event is emitted until an approver approves it, so we need to infer the state based on `isProposalPassing`

### CODE REVIEW

File: src/features/governance/components/Proposal.tsx [hunk 1]
```diff
@@ -119,14 +120,14 @@ function ProposalChainData({ propData }: { propData: MergedProposalData }) {
           <ProposalUpvotersTable propData={propData} />
         </div>
       )}
-      {stage >= ProposalStage.Referendum && (
+      {stage >= ProposalStage.Approval && (
```
Comment (aaronmgdr) [inline src/features/governance/components/Proposal.tsx]: why this? can only vote after referendum

**Review by aaronmgdr — APPROVED** [review]
