### PR TITLE
fix: explorer api

### LINKED ISSUE #323: Listing group stakers and delegate delegators is not working
Image

Image

### PR DESCRIPTION
**Pull request by nicolasbrugneaux**
[Closes #323]

Reasoning: celoscan API stopped working straight up. Tried using etherscan-v2 but the API_KEY just wouldnt be acknowledged as valid, so I migrated to celo.blockscout.com

### CODE REVIEW

File: src/features/explorers/blockscout.ts [hunk 1]
```diff
@@ -2,55 +2,65 @@ import { config } from 'src/config/config';
...
-  while (latestQueryLength === CELO_SCAN_MAX_RESULTS) {
-    page++;
-    baseParams.set('page', page.toString());
+  while (latestQueryLength > 0 && latestQueryLength === BLOCKSCOUT_MAX_RESULTS) {
+    const lastBlockTS = parseInt(result.at(-1)!.timeStamp, 16) * 1000;
+    if (lastBlockTS + 5_000 > Date.now()) {
+      break;
+    }
+    const nextBlock = BigInt(result.at(-1)!.blockNumber!) + BigInt(1);
+    params.set('fromBlock', nextBlock.toString());
```
Comment (nicolasbrugneaux) [inline src/features/explorers/blockscout.ts:41]: That's the major change, blockscout doesn't seem to have paging, so I consider the query finished if the last blockscout query's last item has a block more recent than 5 seconds ago

File: src/features/explorers/blockscout.ts [hunk 2]
```diff
@@ -2,55 +2,65 @@ import { config } from 'src/config/config';
 import { links } from 'src/config/links';
 import { fetchWithTimeout, retryAsync, sleep } from 'src/utils/async';
 import { logger } from 'src/utils/logger';
+import { celo } from 'viem/chains';
 import { ExplorerResponse, TransactionLog } from './types';
 
-// celoscan has a limit of 1000 results per query https://docs.celoscan.io/api-endpoints/logs
-const CELO_SCAN_MAX_RESULTS = 1000;
+// Blockscout has a limit of 1000 results per query https://docs.blockscout.com/devs/apis/rpc/logs
```
Comment (aaronmgdr) [inline src/features/explorers/blockscout.ts:8]: still true?

File: src/features/staking/page.tsx [hunk 3]
```diff
@@ -337,6 +337,8 @@ function Stakers({ group }: { group?: ValidatorGroup }) {
     return sortAndCombineChartData(rawData);
   }, [stakers, isLoading]);
 
+  console.log({ stakers, isLoading, chartData });
+
```
Comment (aaronmgdr) [inline src/features/staking/page.tsx:341]: kill

File: src/features/explorers/blockscout.ts (hunk 2 above)
Comment (nicolasbrugneaux) [reply src/features/explorers/blockscout.ts:8]: yes
