### PR TITLE
fix to enable vote delegatee to vote without needing to also lock

### LINKED ISSUE #160: Can't vote with delegated voting power
## Description

I'm connected with this address that has voting power `0x3779CF289d8161Cd6679696D10647FBa2cb0ef50` but the interface doesn't let me vote because I don't have Celo locked.

Image

But the UI 

## Environment

- Celo Mondo app version
- Operating System
- Browser
- Wallet

### PR DESCRIPTION
**Pull request by aaronmgdr**
allow voting with only delegated votes (non personally locked)

fix #160

### CODE REVIEW

**Comment by aaronmgdr** [comment]
also going to the stake page still allows locking your won celo too

File: src/app/governance/page.tsx [hunk 1]
```diff
@@ -69,6 +68,8 @@ function ProposalList() {
     };
   }, [proposals]);
 
+  const votingPower = useGovernanceVotingPower(address);
```
Comment (nicolasbrugneaux) [inline src/app/governance/page.tsx:71]: nit: since you're not using the loading and/or the error return values, maybe 
```suggestion
  const { votingPower } = useGovernanceVotingPower(address);
```

to make the following code neater

**Review by nicolasbrugneaux — APPROVED** [review]

File: src/app/governance/page.tsx (hunk 1 above)
Comment (aaronmgdr) [reply src/app/governance/page.tsx]: dobra
